static_erasure: mirror-3-dc

host_configs:
- drive:
  - path: /dev/disk/by-partlabel/ydb_disk_ssd_01
    type: SSD
  - path: /dev/disk/by-partlabel/ydb_disk_ssd_02
    type: SSD
  - path: /dev/disk/by-partlabel/ydb_disk_ssd_03
    type: SSD
  host_config_id: 1

hosts:
- host: ydb-node-zone-a.local
  host_config_id: 1
  location:
    body: 1
    data_center: zone-1
    rack: '1'
  node_id: 1
- host: ydb-node-zone-b.local
  host_config_id: 1
  location:
    body: 2
    data_center: zone-2
    rack: '2'
  node_id: 2
- host: ydb-node-zone-c.local
  host_config_id: 1
  location:
    body: 3
    data_center: zone-3
    rack: '3'
  node_id: 3

domains_config:
  domain:
  - name: Root
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: 1
        erasure_species: mirror-3-dc
        geometry:
          domain_level_begin: 10
          domain_level_end: 256
          realm_level_begin: 10
          realm_level_end: 20
        kind: ssd
        pdisk_filter:
        - property:
          - type: SSD
        vdisk_kind: Default
  security_config:
    enforce_user_token_requirement: false
  state_storage:
  - ring:
      node:
      - 1
      - 2
      - 3
      nto_select: 3
    ssid: 1

blob_storage_config:
  service_set:
    groups:
    - erasure_species: mirror-3-dc
      rings:
      - fail_domains:
        - vdisk_locations:
          - node_id: 1
            path: /dev/disk/by-partlabel/ydb_disk_ssd_01
            pdisk_category: SSD
        - vdisk_locations:
          - node_id: 2
            path: /dev/disk/by-partlabel/ydb_disk_ssd_02
            pdisk_category: SSD
        - vdisk_locations:
          - node_id: 3
            path: /dev/disk/by-partlabel/ydb_disk_ssd_03
            pdisk_category: SSD
      - fail_domains:
        - vdisk_locations:
          - node_id: 1
            path: /dev/disk/by-partlabel/ydb_disk_ssd_01
            pdisk_category: SSD
        - vdisk_locations:
          - node_id: 2
            path: /dev/disk/by-partlabel/ydb_disk_ssd_02
            pdisk_category: SSD
        - vdisk_locations:
          - node_id: 3
            path: /dev/disk/by-partlabel/ydb_disk_ssd_03
            pdisk_category: SSD
      - fail_domains:
        - vdisk_locations:
          - node_id: 1
            path: /dev/disk/by-partlabel/ydb_disk_ssd_01
            pdisk_category: SSD
        - vdisk_locations:
          - node_id: 2
            path: /dev/disk/by-partlabel/ydb_disk_ssd_02
            pdisk_category: SSD
        - vdisk_locations:
          - node_id: 3
            path: /dev/disk/by-partlabel/ydb_disk_ssd_03
            pdisk_category: SSD

channel_profile_config:
  profile:
  - channel:
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    profile_id: 0

actor_system_config:
  cpu_count: 6
  node_type: STORAGE
  use_auto_config: true

